export default {
  /* 3rd-party API contants */
  GET_NEWS: 'GET_NEWS',
  GET_USER_LOCATION: 'GET_USER_LOCATION',


  /* Authentication constants */
  CREATE_USER: 'CREATE_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  CONFIRM_USER: 'CONFIRM_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  AUTH_ANONYMOUS_USER: 'AUTH_ANONYMOUS_USER',
  GET_CURRENT_SESSION: 'GET_CURRENT_SESSION',

  /* Test constant for development */
  TEST: 'TEST'

};
