export default {
  /* 3rd-party API contants */
  GET_NEWS_FOR_AUTHORIZED_USER: 'GET_NEWS_FOR_AUTHORIZED_USER',
  GET_NEWS_FOR_UNAUTHORIZED_USER: 'GET_NEWS_FOR_UNAUTHORIZED_USER',
  GET_USER_LOCATION: 'GET_USER_LOCATION',
  GET_NEWS_BY_TOPIC: 'GET_NEWS_BY_TOPIC',

  /* Authentication constants */
  CREATE_USER: 'CREATE_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  CONFIRM_USER: 'CONFIRM_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  AUTH_ANONYMOUS_USER: 'AUTH_ANONYMOUS_USER',
  GET_CURRENT_SESSION: 'GET_CURRENT_SESSION',
  CHANGE_USER_PASSWORD: 'CHANGE_USER_PASSWORD',
  FORGOT_USER_PASSWORD: 'FORGOT_USER_PASSWORD',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  DELETE_USER_ACCOUNT: 'DELETE_USER_ACCOUNT',

  /* Test constant for development */
  POST_NOTE: 'POST_NOTE',
  UPDATE_USER_DB_INFO: 'UPDATE_USER_DB_INFO',
  CREATE_USER_DB_INFO: 'CREATE_USER_DB_INFO',
  GET_CURRENT_USER_DB_INFO: 'GET_CURRENT_USER_DB_INFO',

  /* Not yet set up */
  DELETE_YOUR_PROFILE: 'DELETE_YOUR_PROFILE'
};
